Update DB-prov.yml

diff --git a/.github/workflows/DB-prov.yml b/.github/workflows/DB-prov.yml
--- a/.github/workflows/DB-prov.yml
+++ b/.github/workflows/DB-prov.yml
@@ -44,6 +44,12 @@ jobs:
         # Try to get the existing Security Group ID based on the name. If it doesn't exist, create one.
         SECURITY_GROUP_ID=$(aws ec2 describe-security-groups --filters Name=group-name,Values=${{ vars.DB_SECURITY_GROUP_NAME }} | jq -r '.SecurityGroups[0].GroupId' || aws ec2 create-security-group --group-name ${{ vars.DB_SECURITY_GROUP_NAME }} --description "Security group for ${{ vars.DB_NAME }}" --vpc-id ${{ vars.VPC_ID }} | jq -r '.GroupId')
         
+        # Ensure the ID is valid
+        if [[ -z "$SECURITY_GROUP_ID" || "$SECURITY_GROUP_ID" == "null" ]]; then
+          echo "Failed to retrieve or create security group."
+          exit 1
+        fi
+    
         echo "Using Security Group ID: $SECURITY_GROUP_ID"
     
         PORT=$(if [ "${{ github.event.inputs.db_engine }}" == "postgres" ]; then echo "5432"; else echo "3306"; fi)
